name: Selenium tests for CI/CD
on: [push, workflow_dispatch]
env:
  USERNAME: ${{ secrets.USERNAME }} 
  PASSWORD: ${{ secrets.PASSWORD }} 
  
jobs:     
 selenium-run:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Browser setup
           uses: browser-actions/setup-chrome@v1
         - run: chrome --version

         - name: Npm Updates
           run: npm install  

         - name: Selenium tests
           run: npm test