name: Selenium tests for CI/CD
on: [push, workflow_dispatch]
env:
  USERNAME: ${{ secrets.USERNAME }} 
  PASSWORD: ${{ secrets.PASSWORD }} 
  
jobs:     
 selenium-run:
    runs-on: ubuntu-latest
    steps:
         - name: Checkout
           uses: actions/checkout@v3

         - uses: browser-actions/setup-chrome@v1
           with:
             chrome-version: 120
             install-chromedriver: true

         - name: Npm Updates
           run: npm install  

         - name: Selenium tests
           run: npm run test